### PR TITLE
Fix child might be undefined

### PR DESCRIPTION
**Pull request by mlabrum**
when using JSX and doing something like...

`{this.props.test ? <Text>YAY</Text> : null}`

This library will error when accessing `child.props`

### CODE REVIEW

**Comment by nikhilaravi** [comment]
thanks for this fix @mlabrum! I'll update the version with all these small fixes and re-publish!

**Comment by mlabrum** [comment]
Thanks :D

**Comment by nikhilaravi** [comment]
@mlabrum I've republished to 1.3.6! 🎉  Thanks for your contributions and apologies for our slow responses! :)

**Comment by mlabrum** [comment]
:D that's ok, real life gets in the way sometimes.... I'm glad I can give something back :)

**Pull request merged**
